### ISSUE TITLE
why an array?

### ISSUE THREAD

**Issue by stevenvachon** [jadejs/void-elements#5]
Maps have faster lookups than arrays

**Comment by TimothyGu** [comment]
Why not an array? What will the hash values be? Arrays are *designed* for this kind of tables.

**Comment by stevenvachon** [comment]
`{ key:true }` would work just fine. Arrays are designed to be used based on their use. In this case, searching is the primary purpose, for which array is slower.

**Comment by TimothyGu** [comment]
Seems to be true:

```js
// old.js

module.exports = [
  "area",
  "base",
  "br",
  "col",
  "embed",
  "hr",
  "img",
  "input",
  "keygen",
  "link",
  "menuitem",
  "meta",
  "param",
  "source",
  "track",
  "wbr"
];
```

```js
// new.js
module.exports = {
  "area": true,
  "base": true,
  "br": true,
  "col": true,
  "embed": true,
  "hr": true,
  "img": true,
  "input": true,
  "keygen": true,
  "link": true,
  "menuitem": true,
  "meta": true,
  "param": true,
  "source": true,
  "track": true,
  "wbr": true
};
```

```bench.js
var suite = new (require('benchmark').Suite)
  , o = require('./index')
  , n = require('./new')
  , RUN_COUNT = 10000

suite
  .add('array', function () {
    for (var i = 0; i < RUN_COUNT; i++) {
      o.indexOf('span')
      o.indexOf('img')
    }
  })
  .add('obj', function () {
    for (var i = 0; i < RUN_COUNT; i++) {
      n.span
      n.img
    }
  })
  .on('cycle', function(event) {
    console.log(String(event.target))
  })
  .run()
```

```sh
$ npm install benchmark
$ node bench.js
array x 955 ops/sec ±0.30% (100 runs sampled)
obj x 20,840 ops/sec ±0.48% (99 runs sampled)
```

But in any case the use of array in this module will hardly ever be the bottleneck of an application.

I'll leave the final weight of decision to @hemanth.

**Comment by stevenvachon** [comment]
`hasOwnProperty()` is even faster again

**Comment by TimothyGu** [comment]
@stevenvachon said:

> hasOwnProperty() is even faster again

Nope.

```js
// bench.js

var suite = new (require('benchmark').Suite)
  , o = require('./index')
  , n = require('./new')
  , RUN_COUNT = 10000

suite
  .add('array', function () {
    for (var i = 0; i < RUN_COUNT; i++) {
      o.indexOf('span')
      o.indexOf('img')
    }
  })
  .add('obj', function () {
    for (var i = 0; i < RUN_COUNT; i++) {
      n.hasOwnProperty('span')
      n.hasOwnProperty('img')
    }
  })
  .on('cycle', function(event) {
    console.log(String(event.target))
  })
  .run()
```

```sh
$ node bench.js 
array x 956 ops/sec ±1.13% (100 runs sampled)
obj x 1,443 ops/sec ±0.26% (101 runs sampled)
```

**Comment by stevenvachon** [comment]
Oh, yes, because you had `n.span` instead of `n["span"]`. In most cases, this library would be part of a loop and would use a string syntax.

The results are kind of dramatic, especially compared with `Array.prototype.indexOf()`:
http://jsperf.com/object-hasownproperty-vs-array-indexof/2

**Comment by TimothyGu** [comment]
@stevenvachon said:

> Oh, yes, because you had `n.span` instead of `n["span"]`.

True.

**Comment by TimothyGu** [comment]
`[]` is almost as fast as directly referencing the key here.

**Comment by hemanth** [comment]
@TimothyGu Merged your PR. :)

@stevenvachon Thank you!

**Comment by stevenvachon** [comment]
@TimothyGu in my test, it was so fast that it totally skewed my benchmark, heheh: http://jsperf.com/object-hasownproperty-vs-array-indexof/12

Thank you both! You guys work fast

**Comment by TimothyGu** [comment]
@stevenvachon LOL. Expect to see a hopefully faster Jade 1.9.2 soon.

**Comment by hemanth** [comment]
![](http://media2.giphy.com/media/iLUwVbWFVnaBG/200.gif)

**Comment by stevenvachon** [comment]
Awesome :)

Built for speed!
